[2025-04-18T21:25:40.101+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T21:25:40.151+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt.run_dbt_deps manual__2025-04-18T19:56:57.798037+00:00 [queued]>
[2025-04-18T21:25:40.184+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt.run_dbt_deps manual__2025-04-18T19:56:57.798037+00:00 [queued]>
[2025-04-18T21:25:40.185+0000] {taskinstance.py:2867} INFO - Starting attempt 8 of 9
[2025-04-18T21:25:40.223+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_dbt_deps> on 2025-04-18 19:56:57.798037+00:00
[2025-04-18T21:25:40.235+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=48345) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T21:25:40.233+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'run_dbt', 'run_dbt_deps', 'manual__2025-04-18T19:56:57.798037+00:00', '--job-id', '660', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_model.py', '--cfg-path', '/tmp/tmpc48nin5r']
[2025-04-18T21:25:40.236+0000] {standard_task_runner.py:72} INFO - Started process 48346 to run task
[2025-04-18T21:25:40.236+0000] {standard_task_runner.py:105} INFO - Job 660: Subtask run_dbt_deps
[2025-04-18T21:25:40.315+0000] {task_command.py:467} INFO - Running <TaskInstance: run_dbt.run_dbt_deps manual__2025-04-18T19:56:57.798037+00:00 [running]> on host f21ba0bbe878
[2025-04-18T21:25:40.428+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_dbt' AIRFLOW_CTX_TASK_ID='run_dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T19:56:57.798037+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T19:56:57.798037+00:00'
[2025-04-18T21:25:40.429+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T21:25:40.457+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-18T21:25:40.461+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt deps']
[2025-04-18T21:25:40.477+0000] {subprocess.py:99} INFO - Output:
[2025-04-18T21:25:43.730+0000] {subprocess.py:106} INFO - [0m21:25:43  Running with dbt=1.8.1
[2025-04-18T21:25:44.746+0000] {subprocess.py:106} INFO - [0m21:25:44  Installing dbt-labs/dbt_utils
[2025-04-18T21:25:48.421+0000] {subprocess.py:106} INFO - [0m21:25:48  Installed from version 1.3.0
[2025-04-18T21:25:48.422+0000] {subprocess.py:106} INFO - [0m21:25:48  Up to date!
[2025-04-18T21:25:49.264+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-18T21:25:49.293+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T21:25:49.293+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=run_dbt, task_id=run_dbt_deps, run_id=manual__2025-04-18T19:56:57.798037+00:00, execution_date=20250418T195657, start_date=20250418T212540, end_date=20250418T212549
[2025-04-18T21:25:49.349+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T21:25:49.380+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-18T21:25:49.383+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
