[2025-04-18T19:59:21.484+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T19:59:21.505+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_dbt.run_dbt_deps manual__2025-04-18T19:56:57.798037+00:00 [queued]>
[2025-04-18T19:59:21.513+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_dbt.run_dbt_deps manual__2025-04-18T19:56:57.798037+00:00 [queued]>
[2025-04-18T19:59:21.514+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 3
[2025-04-18T19:59:21.530+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_dbt_deps> on 2025-04-18 19:56:57.798037+00:00
[2025-04-18T19:59:21.540+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=42028) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T19:59:21.540+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'run_dbt', 'run_dbt_deps', 'manual__2025-04-18T19:56:57.798037+00:00', '--job-id', '622', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_model.py', '--cfg-path', '/tmp/tmprb91l1ns']
[2025-04-18T19:59:21.541+0000] {standard_task_runner.py:72} INFO - Started process 42029 to run task
[2025-04-18T19:59:21.542+0000] {standard_task_runner.py:105} INFO - Job 622: Subtask run_dbt_deps
[2025-04-18T19:59:21.598+0000] {task_command.py:467} INFO - Running <TaskInstance: run_dbt.run_dbt_deps manual__2025-04-18T19:56:57.798037+00:00 [running]> on host f21ba0bbe878
[2025-04-18T19:59:21.686+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_dbt' AIRFLOW_CTX_TASK_ID='run_dbt_deps' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T19:56:57.798037+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T19:56:57.798037+00:00'
[2025-04-18T19:59:21.687+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T19:59:21.702+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-18T19:59:21.703+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt deps']
[2025-04-18T19:59:21.711+0000] {subprocess.py:99} INFO - Output:
[2025-04-18T19:59:24.168+0000] {subprocess.py:106} INFO - [0m19:59:24  Running with dbt=1.8.1
[2025-04-18T19:59:24.950+0000] {subprocess.py:106} INFO - [0m19:59:24  Installing dbt-labs/dbt_utils
[2025-04-18T19:59:28.751+0000] {subprocess.py:106} INFO - [0m19:59:28  Installed from version 1.3.0
[2025-04-18T19:59:28.752+0000] {subprocess.py:106} INFO - [0m19:59:28  Up to date!
[2025-04-18T19:59:29.547+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-18T19:59:29.572+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T19:59:29.573+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=run_dbt, task_id=run_dbt_deps, run_id=manual__2025-04-18T19:56:57.798037+00:00, execution_date=20250418T195657, start_date=20250418T195921, end_date=20250418T195929
[2025-04-18T19:59:29.629+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T19:59:29.661+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-18T19:59:29.664+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
