[2025-04-18T12:11:24.098+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T12:11:24.194+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_gcs.download_csv_from_kaggle scheduled__1991-01-01T00:00:00+00:00 [queued]>
[2025-04-18T12:11:24.242+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_gcs.download_csv_from_kaggle scheduled__1991-01-01T00:00:00+00:00 [queued]>
[2025-04-18T12:11:24.256+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-18T12:11:24.307+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_csv_from_kaggle> on 1991-01-01 00:00:00+00:00
[2025-04-18T12:11:24.329+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_gcs', 'download_csv_from_kaggle', 'scheduled__1991-01-01T00:00:00+00:00', '--job-id', '576', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_to_gcs.py', '--cfg-path', '/tmp/tmphuha8b5p']
[2025-04-18T12:11:24.344+0000] {standard_task_runner.py:105} INFO - Job 576: Subtask download_csv_from_kaggle
[2025-04-18T12:11:24.332+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2735) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-18T12:11:24.360+0000] {standard_task_runner.py:72} INFO - Started process 2739 to run task
[2025-04-18T12:11:24.496+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_to_gcs.download_csv_from_kaggle scheduled__1991-01-01T00:00:00+00:00 [running]> on host f21ba0bbe878
[2025-04-18T12:11:24.908+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_gcs' AIRFLOW_CTX_TASK_ID='download_csv_from_kaggle' AIRFLOW_CTX_EXECUTION_DATE='1991-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__1991-01-01T00:00:00+00:00'
[2025-04-18T12:11:24.913+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T12:11:24.980+0000] {logging_mixin.py:190} INFO - Dataset URL: https://www.kaggle.com/datasets/viggo123/data-fight-usa-dataset
[2025-04-18T12:12:18.590+0000] {job.py:229} INFO - Heartbeat recovered after 33.61 seconds
[2025-04-18T12:12:35.963+0000] {job.py:229} INFO - Heartbeat recovered after 12.25 seconds
[2025-04-18T12:13:33.523+0000] {job.py:229} INFO - Heartbeat recovered after 39.76 seconds
[2025-04-18T12:14:12.312+0000] {job.py:229} INFO - Heartbeat recovered after 11.57 seconds
[2025-04-18T12:14:35.075+0000] {job.py:229} INFO - Heartbeat recovered after 17.70 seconds
[2025-04-18T12:14:35.183+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9. For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2025-04-18T12:14:35.400+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-04-18T12:14:38.794+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T12:14:38.807+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
